---
# Основные пути
app_base_dir: /opt/deploy-elk
app_config_dir: "{{ app_base_dir }}/configs"

# Пути для компонентов
elasticsearch_config_dir: "{{ app_config_dir }}/elasticsearch"
logstash_config_dir: "{{ app_config_dir }}/logstash"
logstash_pipelines_config_dir: "{{ logstash_config_dir }}/pipelines"
kibana_config_dir: "{{ app_config_dir }}/kibana"

# Локальные пути к файлам (относительно роли)
local_config_dir: "files"
local_elasticsearch_config: "{{ local_config_dir }}/elasticsearch/config.yml"
local_logstash_config: "{{ local_config_dir }}/logstash/config.yml"
local_pipeline: "{{ local_config_dir }}/logstash/pipelines.yml"
local_pipeline_config: "{{ local_config_dir }}/logstash/pipelines/nginx_logstash.conf"
local_kibana_config: "{{ local_config_dir }}/kibana/config.yml"

# Локальные пути к docker-compose файлам (относительно роли)
local_compose_file: "../../../../docker/deploy-elk/docker-compose.yml"